---
abstract: 'runs another program with environment modified according to envfile'
author:
  - 'xaicron <xaicron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-envfile
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/xaicron/p5-App-envfile.git
version: 0.04
