---
abstract: 'runs another program with environment modified according to envfile'
author:
  - 'xaicron <xaicron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-envfile
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  App::envfile:
    file: lib/App/envfile.pm
    version: 0.07
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/xaicron/p5-App-envfile/issues
  homepage: https://github.com/xaicron/p5-App-envfile
  repository: git://github.com/xaicron/p5-App-envfile.git
version: 0.07
x_contributors:
  - 'Urabe, Shyuohei <shyouhei@ruby-lang.org>'
  - 'xaicron <xaicron@gmail.com>'
